#+STARTUP: fold

* Compile & Link
g++ -Wall -Werror -std=c++14 test.cpp -o test
* Preprocessor
- #include "any.h"
- #define find replace
- #if 1 /*code*/ #endif
** Windows(Visual Studio)
right click on project -> Properties -> C/C++ -> Preprocessor -> Preprocess to a file: yes
** Linux
g++ -E test.cpp -o hello.i
g++ hello.i -o test
* Compiler
** Windows
right click on project -> Properties -> C/C++ -> Output Files -> Assembler Output:Assembly-Only-Listing
** Linux
*** Readable
g++ test.cpp -S -o hello.s
*** Non-Readable
g++ -c test.cpp
g++ -c main.cpp
g++ -c mainexe main.o test.o

- Check for dependencies
  g++ -MM main.cpp
* Optimization(-O,-O0,-O1,-O2,-O3,-Os,-Ofast)
** Windows
right click on project -> Properties -> C/C++ -> Configuration:Debug -> Optimization:Maximze Speed
right click on project -> Properties -> C/C++ -> Code Generation -> Basic Runtime Checks:Default
** Linux
g++ test.cpp -S -O2 -o hello.s
** Pragma
#pragma GCC optimize("Ofast")
#pragma GCC target("avx,avx2,fma")
** vector optimize
#+begin_src C++ :results output
#include<iostream>
#include<vector>
using namespace std;
struct Vertex{
    float x,y,z;
    Vertex(float x,float y,float z):x(x),y(y),z(z){}
    Vertex(const Vertex& vertex):x(vertex.x),y(vertex.y),z(vertex.z){
        cout<<"copied"<<endl;
        }
    };
int main(){
    vector<Vertex> vertices;
    vertices.reserve(3);
    cout<<vertices.capacity()<<endl;
    // vertices.push_back({1,2,3});
    // vertices.push_back({4,5,6});
    // vertices.push_back(Vertex(7,8,9));
    vertices.emplace_back(1,2,3);//moves
    Vertex v{4,5,6};
    vertices.emplace_back(v);//copied
    vertices.emplace_back(Vertex(7,8,9));//copied
    }
#+end_src

#+RESULTS:
: 3
: copied
: copied

* Linker
** Custom entry point
*** Windows
right click on project -> Properties -> Linker -> Advanced -> Entry Point:(type function name)
*** Linux
**** Only for C
#+begin_src C :results output
#include <stdio.h>
#include <stdlib.h>
int mymain() {
    printf("hello");
    exit(0);
}
#+end_src

- gcc -nostartfiles -Wl,--entry=mymain -o main.out main.c

** Linking Error(g++ main.cpp Math.cpp -o main)
*** Wrong Declaration
- Wrong return type
- Wrong parameter type
- Wrong parameter number
*** Declaration but no Defination
- Without defination function declaration is not cause error(linking error), you have to call to get error. You don't need to use main function, any kind of function use to get error.
*** Conflict
- In Math.cpp
#+begin_src C++ :results output
int math(int a,int b){
    int result = a+b;
    return result;
}
#+end_src
- In main.cpp
#+begin_src C++ :results output
#include<iostream>
using namespace std;
static int math(int,int);
int main()
{
    cout<<"hello "<<math(2,3);
    return 0;
}
int math(int a,int b){
    return a*b;
}
#+end_src

#+RESULTS:
: hello 6

+ Static function without class means this function for made only for this cpp file.

- In Math.cpp
#+begin_src C++ :results output
static int math(int a,int b){
    int result = a+b;
    return result;
}
#+end_src
- In main.cpp
#+begin_src C++ :results output
#include<iostream>
using namespace std;
int math(int,int);
int main()
{
    cout<<"hello"<<math(2,3);
    return 0;
}
#+end_src
- Result is linking error

*** With Defination header file
- In log.h
#+begin_src C++ :results output
void log(const char* message){std::cout<<message<<std::endl;}
#+end_src
- In Math.cpp
#+begin_src C++ :results output
#include "log.h"
int math(int a,int b){
    log("math");
    int result = a+b;
    return result;
}
#+end_src
- In main.cpp
#+begin_src C++ :results output
#include<iostream>
#include "log.h"
using namespace std;
static int math(int,int);
int main()
{
    log("main");
    cout<<"hello "<<math(2,3);
    return 0;
}
#+end_src
- Result is linking error
- Use static or Inline(not always work, it's a requst) before function defination in log.h
* Pause
- system("pause>nul");
- std::cin.get();
* Variables
- Char change numeric value to alphabet through ascii, int change alphabet value to numeric through ascii.
- Use f to define variable as a float, or it consider as double.
- Bit can't be represent as a address, only bytes can.
* Loop
#+begin_src C++ :results output
#include<iostream>
using namespace std;
int main(){
  int i = 0;
  bool condition = true;
  for (; condition;) {
    cout << "ok" << endl;
    i++;
    if (!(i < 5)) {
      condition = false;
    }
  }
  return 0;
}
#+end_src

#+RESULTS:
: ok
: ok
: ok
: ok
: ok
* Pointer
int var = 8;
double* ptr = (double*)&var;
void* ptr = &var;
*ptr = 10; //error

char* buffer = new char[8];
memset(buffer,0,8);

* Array vs Pointer
- Array allocate memory and hold address but, pointer just hold address
Yes strcmp should be used there but it works in the case because when he wrote "Hello" in the if condition that is a character constant in the static memory and the variable pointer ptr points to a "Hello" in the same static memory and they basically have the same address, so basically he just compared the address that ptr holds to the address of "Hello" and in the static memory they both are at the same address.
To better understand this consider the following code:
#+begin_src C++ :results output
#include<iostream>
int main(){
    const char *ptr = "Hello World!";
    const char *ptr2= "Hello World!";
    if (ptr == ptr2)
        std::cout << "Same!";
    else
        std::cout << "Not Same!";
    return 0;
}
#+end_src

#+RESULTS:
: Same!

This will print Same! because "Hello World!" is a character constant and stored in the static memory and both the pointers point to the same address hence ptr is infact equal to ptr2  ( the address they hold is same).
Now consider this code.
#+begin_src C++ :results output
#include<iostream>
int main(){
    const char ptr[] = "Hello World!";
    const char ptr2[] = "Hello World!";
    if (ptr == ptr2)
        std::cout << "Same!";
    else
        std::cout << "Not Same!";
    return 0;
}
#+end_src

#+RESULTS:
: Not Same!

This will give "Not Same!" because this time it is not a character constant it is a character array and it is stored on the stack and both pointers point to a different address.
So this time ptr is not holding the same address as ptr2 though the content is same.
* Enum vs Class enum
#+begin_src C++ :results output
enum Color { red, green, blue };                    // plain enum
enum Card { red_card, green_card, yellow_card };    // another plain enum
enum class Animal { dog, deer, cat, bird, human };  // enum class
enum class Mammal { kangaroo, deer, human };        // another enum class

void fun() {

    // examples of bad use of plain enums:
    Color color = Color::red;
    Card card = Card::green_card;

    int num = color;    // no problem

    if (color == Card::red_card) // no problem (bad)
        cout << "bad" << endl;

    if (card == Color::green)   // no problem (bad)
        cout << "bad" << endl;

    // examples of good use of enum classes (safe)
    Animal a = Animal::deer;
    Mammal m = Mammal::deer;

    int num2 = a;   // error
    if (m == a)         // error (good)
        cout << "bad" << endl;

    if (a == Mammal::deer) // error (good)
        cout << "bad" << endl;

}
#+end_src

#+begin_src C++ :results output
enum vehicle
{
    Car,
    Bus,
    Bike,
    Autorickshow
};
enum FourWheeler
{
    Car,        // error C2365: 'Car': redefinition; previous definition was 'enumerator'
    SmallBus
};

enum class Editor
{
    vim,
    eclipes,
    VisualStudio
};
enum class CppEditor
{
    eclipes,       // No error of redefinitions
    VisualStudio,  // No error of redefinitions
    QtCreator
};
#+end_src

#+begin_src C++ :results output
#include<iostream>
using std::cout;
class animal {
public:
    enum pet { cat, dog, mouse };
    pet mypet=dog;
};
int main(){
    if (animal::mouse == 2) {
    cout << "hello";
    }
}
#+end_src

#+RESULTS:
: hello

* Size of Int
#+begin_src C++ :results output
#include<iostream>
using std::cout;
int main(){
    cout<<sizeof(int16_t);
    }
#+end_src

#+RESULTS:
: 2
* String Literals
#+begin_src C++ :results output
#include<iostream>
using std::cout;
int main(){
    char *name = (char*)"Real"; // not changable
    char name1[] = "Poser"; // changable
    name1[2]= 'w';
    cout<<name<<*(name+2)<<name1;
    }
#+end_src

#+RESULTS:
: RealaPower

#+begin_src C++ :results output
#include<iostream>
using std::string;
int main(){
    const char *name0 = u8"Real"; // 1 bytes
    const wchar_t *name1 = L"Real"; // 2 or 4 bytes, compilar decide
    const char16_t *name2 = u"Real"; // 2 bytes
    const char32_t *name3 = U"Real"; // 4 bytes
    const char *ex = R"(line1
        line2
        line3)"; // without escape sequence
    std::cout<<ex;

    string name4 = u8"Real"; // 1 bytes
    std::wstring name5 = L"Real"; // 2 or 4 bytes, compilar decide
    std::u16string name6 = u"Real"; // 2 bytes
    std::u32string name7 = U"Real"; // 4 bytes
    }
#+end_src

* Operator Overloading
#+begin_src C++ :results output
#include<iostream>
using namespace std;
class vector{
    float x,y;
    public:
        vector(){}
        vector(float a,float b):x(a),y(b){}
        // ADD
        vector add(const vector& other){
            return vector(x+other.x, y+other.y);
            }
        vector operator+(const vector& other){
            return add(other);
            }
        // MULTIPLY
        vector multiply(const vector& other){
            return *this *(other);
            // return (*this).operator*(other);
            // return operator*(other);
            }
        vector operator*(const vector& other){
            return vector(x*other.x, y*other.y);
            }
        // BOOLEAN
        bool operator==(const vector& other){
            return x==other.x && y==other.y;
            }
        bool operator!=(const vector& other){
            return !(*this==other);
            }

        friend void printvector(const vector&);
};
void printvector(const vector& v){
    cout<<v.x<<endl<<v.y;
    }
int main(){
    vector v1(3.5,4.2);
    vector v2(8.1,3.7);
    vector v3(9.6,7.2);
    vector v4= v1+(v2.multiply(v3));
    printvector(v4);
    bool b=v2!=v3;
    cout<<endl<<b;
    }
#+end_src
* Deep Copy
#+begin_src C++ :results output
#include<iostream>
#include<string.h>
using namespace std;
class myString{
    char *my_buffer;
    unsigned int my_string_size;
    public:
        myString(const char *s){
            my_string_size=strlen(s);
            my_buffer=new char[my_string_size+1];
            memcpy(my_buffer,s,my_string_size);
            my_buffer[my_string_size]= *"\0";
            }
        // myString(const myString &str):my_buffer(str.my_buffer),my_string_size(str.my_string_size){}
        // myString(const myString &str){memcpy(this,&str,sizeof(myString))}
        myString(const myString &str):my_string_size(str.my_string_size){
            my_buffer=new char[my_string_size+1];
            memcpy(my_buffer,str.my_buffer,my_string_size+1);
            }
        ~myString(){
            delete []my_buffer;
            }
        char& operator [](unsigned int index){return my_buffer[index];}
        friend ostream &operator<<(ostream&,const myString&);
};
ostream &operator <<(ostream &dout,const myString &st){
    dout<<st.my_buffer;
    return(dout);
}
int main(){
    myString s1="Dragon";
    myString s2=s1;
    s2[1]= *"a";
    s2[2]= *"r";
    cout<<s1<<endl<<s2;
    }
#+end_src

#+RESULTS:
: Dragon
: Dargon

* Arrow operator
#+begin_src C++ :results output
#include<iostream>
#include<cstdint>
using namespace std;
struct Vector3{
    float x,z,y;
    };
int main(){
    Vector3* p = new Vector3;
    // uint64_t offset = (uint64_t)&(*(Vector3*)0).y;
    uint64_t offset = ((uint64_t)&((Vector3*)p)->z) - ((uint64_t)p);
    cout<<offset<<endl;
    cout << (int*) &((Vector3*)nullptr) -> z << endl;
    // cout << (intptr_t) &((Vector3*) nullptr) -> z << endl;
    }
#+end_src

#+RESULTS:
: 4
: 0x4

The arrow operator can also be used with "trailing return type" syntax (c++11).

For example:

#+begin_src C++ :results output
auto function1(int value) -> int
{
    return value;
}

// which is the same as:

auto function2(int value) -> decltype(value)
{
    return value;
}

// This is the exact same thing as: (C++14)

decltype(auto) function3(int value)
{
    return value;
}
int main(){}
#+end_src

#+RESULTS:
* Return multiple values
#+begin_src C++ :results output
#include<iostream>
using namespace std;
struct values{int x;float y;};
values fun(bool flg){
    if(flg) return {1,2.5};
    }
int main(){
    values v;
    v=fun(true);
    cout<<v.x<<v.y;
    }
#+end_src

#+RESULTS:
: 12.5
